job_controller/job_controller.go

Creating the interfaces for custom controllers to implement, that is:
```
// DeleteJob deletes the job
DeleteJob(job interface{}) error
// UpdateJobStatus updates the job status and job conditions
UpdateJobStatus(job interface{}, replicas map[common.ReplicaType]*common.ReplicaSpec, jobStatus common.JobStatus) error
// CreateService creates the service
CreateService(job interface{}, service *v1.Service) error
// DeleteService deletes the service
DeleteService(job interface{}, service *v1.Service) error
// CreatePod creates the pod
CreatePod(job interface{}, podTemplate *v1.PodTemplate) error
// DeletePod deletes the pod
DeletePod(job interface{}, pod *v1.Pod) error
// SetClusterSpec sets the cluster spec for the pod
SetClusterSpec(job interface{}, podTemplate *v1.PodTemplate, rtype, index …
```

Define interfaces for common job operators

---

operator/v1/types.go

Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>
part of #11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/13)

Added schedulingPolicy api.

---

job_controller/job.go
job_controller/job_controller.go
job_controller/job_test.go
job_controller/status.go
job_controller/status_test.go
job_controller/test_job_controller.go
util/k8sutil/k8sutil.go

Add more utility functions for job and status. 
This echos what's already available in TF operator.
@terrytangyuan 
@richardsliu 
@johnugeorge
@gaocegege 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/14)

Add more utility functions for job and status

---

operator/v1/types.go

This should be `RestartPolicyExitCode` instead of `ExitCode`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/20)

Fix incorrect name for restart policy exit code

---

test_util/v1/const.go
test_util/v1/pod.go
test_util/v1/service.go
test_util/v1/test_job_util.go
test_util/v1/util.go

Signed-off-by: Ce Gao <gaoce@caicloud.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/27)

chore: Fix package name

---

.travis.yml
job_controller/job.go
job_controller/job_controller.go
job_controller/job_test.go
job_controller/test_job_controller.go

This PR adds utility methods for job reconciliation (part of https://github.com/kubeflow/common/issues/7). Note that part of the code is commented out for now until service reconciliation logic is in place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/24)

Add utility methods for job reconciliation

---

job_controller/job_controller.go
job_controller/pod.go
job_controller/service.go
job_controller/test_job_controller.go

Since we have a common operator, and think the common label keys can also be unified,  so that the custom operator will not need to implement these
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/29)

Unify the label keys

---

job_controller/job_controller.go

First letter of the function names in the comment needs to be capitalized to match their actual names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/32)

Correct function names in the comment

---

job_controller/job.go
job_controller/job_controller.go
job_controller/pod.go
job_controller/test_job_controller.go

Move `UpdateJobStatus` out of ReconcilePods loop, and remove bool arg(`restart`) which can be inferred from `replicas`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/35)

refine arguments of ControllerInterface.UpdateJobStatus

---

job_controller/job.go
job_controller/job_controller.go
job_controller/pod.go
job_controller/service.go
job_controller/test_job_controller.go

Fixes #33 
Removed the PodControl/ServiceControl interfaces.
Changed the associated logic accordingly
@richardsliu @gaocegege @johnugeorge 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/36)

Remove the podControl and serviceControl interfaces

---

job_controller/api/v1/interface.go
job_controller/service.go
job_controller/test_job_controller.go
test_job/v1/test_job_controller.go

We need to get the port name of container for each job, so we would change the port number to port name in the job controller interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/41)

GetDefaultContainerPortNumber to GetDefaultContainerPortName

---

job_controller/api/v1/interface.go
job_controller/job.go
job_controller/test_job_controller.go
test_job/v1/test_job_controller.go

this is related to [issue](https://github.com/kubeflow/common/issues/43). We need to update the job status in the function of updatejobstatus. 
This is a interface for user to implement, and locally test on xgboost operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/44)

[hot-fix-43] change the job status api 

---

job_controller/api/v1/doc.go
job_controller/api/v1/types.go

In the PR https://github.com/kubeflow/tf-operator/pull/1103, we generate SDK using openapi  -> swagger ways, tfjob depends on common repo, the PR is current the openapi generate flag so that the current types can be involved. See more in https://github.com/kubeflow/tf-operator/pull/1103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/49)

Update openapi tag for SDK generating

---

.travis.yml

The deprecation of gometalinter is official so this comment isn't necessary anymore. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/common/50)

Remove unnecessary comment on gometalinter

---

pkg/controller.v1/common/service.go

Address #56 
- Instead of using fixed port to communicate with each other, some frameworks randomly pick up port by worker and use auto-discovery to find entire topology.
- In that case, we only need pod-to-pod communication and don’t need to specify port in headless service.
- This give the flexibility for framework which doesn’t rely on fixed port.
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
I've tested in a controller using this common.

Make container port optional

---

ROADMAP.md

Let's have more discussion here on the training operator 2020 roadmap.
I think most of the operators are pretty stable and major work is to graduate all the other operators to v1 and rewrite operators to use common apis. 
Besides that, we do see some feature request not fulfilled last year and let's have a revisit.
In addition, think big on features/products towards production grade level. 
@terrytangyuan @gaocegege @johnugeorge @rongou @richardsliu @jian-he  @merlintang @suleisl2000   @jlewi

Add distributed training operator roadmap

---

go.mod
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/service.go
pkg/controller.v1/control/pod_control.go
pkg/controller.v1/control/pod_control_test.go
pkg/controller.v1/control/service_control.go
pkg/controller.v1/control/service_control_test.go
pkg/controller.v1/control/service_ref_manager.go
pkg/controller.v1/control/service_ref_manager_test.go
pkg/controller.v1/control/utils.go

Currently, pods/services implementation mixed with jobController together under `common` folder, this is a little messy. 
The reason we want to have separate folder (package name) for it are
1. PodControlInterface is folked from [controller_util.go](https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/controller/controller_utils.go) and we also implement similar codes for service. They are logically separate. For long term, once https://github.com/kubernetes/client-go/issues/332 is merged, we could remove the folder entirely.
2.  Since `PodControlInterface` and `ServiceControlInterface` are internal code base for common project, there's no need for users to import them at all. 
3. Trying to make some changes inside `control` to solve #48. It would be better to file this PR first …

Move Pods/Services control interface to separate folder

---

.travis.yml

We no longer have vendor directories.

Update comments on the use of -ignore flag for goveralls

---

DEVELOPMENT.md

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
This doc gives a development guidance for other developer to easily onboard this. 
It also address @gaocegege's feedback here. 
https://github.com/kubeflow/common/pull/73#issuecomment-616265692
Add a section to remind user don't edit codes from upstream.

Add DEVELOPMENT.md doc

---

docs/prometheus-metrics.md

This provides a detailed outline of the Prometheus metrics we plan to coverage in common operator. Related issue: https://github.com/kubeflow/common/issues/22.
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Add proposal for Prometheus metrics coverage

---

go.mod
pkg/controller.v1/common/pod.go

Not collecting metrics for pod restarted here because that requires additional changes in pod restart logic in other code. We can do that in a follow-up PR.
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Add Prometheus metrics for pod created/deleted/failed

---

pkg/controller.v1/common/job_controller.go

This PR contains the following:
* Captured errors related to pdb/podGroup creations
* Added Prometheus metrics for the creation/deletion of pdb/podGroup
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Add scheduling related Prometheus metrics

---

pkg/apis/common/v1/interface.go
pkg/controller.v1/common/job.go
pkg/controller.v1/common/job_controller.go
pkg/controller.v1/common/job_test.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/service.go
test_job/controller.v1/test_job/test_job_controller.go

The motivation of this PR is to reduce the efforts to build a training job operators. 
1. These are all common CRUD operations and there's no big difference between job operators. We don't have to expose to external for implementation. Instead, this should be inside common libraries or inbuilt controller methods user should not take care of. 
```
GetPodsForJob
GetServiceForJob
CreateService
DeleteService
CreatePod
DeletePod
```
As we bring back control and expectation packages, we have enough utils to implement these methods easily inside `JobController`. 
2. `GetDefaultContainerPortNumber()` is an interface never been used, we reply on `GetDefaultContainerName()` and `GetDefaultContainerPortName ()` to find the port, this is expose to user to make the decision. I think it was brought …

Simplify interfaces and remove useless interfaces

---

pkg/controller.v1/expectation/expectation.go

Resolve #89 
Info level is kind of noisy and debug level is much better
Before
```
INFO[0011] need to create new service: worker-1          job=default.xgboost-dist-iris-test-train replica-type=worker uid=467fb419-962b-11ea-b670-026fb543c17c
INFO[0011] Setting expectations &expectation.ControlleeExpectations{add:1, del:0, key:"default/xgboost-dist-iris-test-train/worker/services", timestamp:time.Time{wall:0xbfa78c778e0631d8, ext:11414609468, loc:(*time.Location)(0x313bcc0)}}
INFO[0011] Update on create function xgboostjob-operator create object xgboost-dist-iris-test-train-worker-1
INFO[0011] Lowered expectations &expectation.ControlleeExpectations{add:-2, del:0, key:"default/xgboost-dist-iris-test-train/worker/pods", timestamp:time.Time{wall:0xbfa78c778a2968f0, ext:11349809202, …
```

Change expectation package log level to debug

---

pkg/apis/common/v1/interface.go
pkg/controller.v1/common/job.go
pkg/controller.v1/common/job_test.go
test_job/controller.v1/test_job/test_job_controller.go

Following methods both have common implementation and user can override them if existing solution doesn't fit. 
1. Add `GetPodsForJob` and `GetServiceForJob` back for kubebuilder based operator.
2. Add `ReconcileJobs`, `ReconcilePods` and `ReconcileServices` into interface. 
3. Expose methods for better customization
This has been tested with mxnet-operator (built with low level informer and lister) and xgboost-operator (built with kubebuilder)
Seems tensorflow operator may have some customizations on reconcile logic, they can override the  methods and still leverage some common methods.

Provides more flexibility for customizations

---

pkg/controller.v1/common/job.go

Resolve #92 #94
1. Skip checking activeDeadline or backoffLimit if job terminated 
2. Add PodGroup reconcile logic

Skip some logics for terminated job and add PodGroup reconcile loop

---

pkg/controller.v1/common/job.go

ref issue: https://github.com/kubeflow/tf-operator/issues/1131

Feat(event): record the tfjob event from the abnormal pod status

---

pkg/controller.v1/common/service.go
pkg/controller.v1/common/service_test.go

Signed-off-by: xieydd chrisydxie@tencent.com
Try to resolve issue #122 .
This has been tested with tf-operator.
```
Worker:
template:
spec:
ports:
- name: test
containerPort: 80
spec:
clusterIP: None
ports:
- name: test
port: 80
protocol: TCP
targetPort: 80
- name: tfjob-port
port: 2222
protocol: TCP
targetPort: 2222
selector:
group-name: kubeflow.org
job-name: dist-mnist-for-e2e-test
replica-index: "0"
replica-type: ps
sessionAffinity: None
type: ClusterIP
```

Make ports more flexiable for customizations

---

pkg/apis/common/v1/interface.go
pkg/controller.v1/common/job.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/service.go
pkg/controller.v1/common/util.go
pkg/controller.v1/common/util_test.go
pkg/controller.v1/expectation/util.go
pkg/util/logger.go
test_job/controller.v1/test_job/test_job_controller.go

change type of rtype to commonv1.ReplicaType 

---

pkg/controller.v1/common/job.go
pkg/controller.v1/common/job_test.go

my implementation refer to 
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/ttlafterfinished/ttlafterfinished_controller.go#L290

optimize the ttl of job

---

pkg/controller.v1/common/job.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/service.go

More appropriate use of expectation:
1. use `RaiseExpectations` in the code to accumulate expectations since `SetExpectations` has no such kind of ability. reset expectation in the beginning of `ReconcileJobs`;
2. expected creation in more appropriate place;
3. add "expectDeletion";
More detailed comments and explanations are presented with codes.

fix(expectation): more appropriate use of expectation

---

.gitignore
pkg/controller.v1/common/util.go
pkg/controller.v1/common/util_test.go

In GenGeneralName, we should use lower case.
In the past we do the conversion outside the function since the replicaType is a string. Now its type is replicaType, thus we should do it in the function.
/cc @terrytangyuan @MartinForReal 
Signed-off-by: cegao <cegao@tencent.com>

fix: Add uppercase support for GenGeneralName

---

pkg/controller.v1/common/job.go

feat(common): support delay pods creation

---

pkg/apis/common/v1/constants.go
pkg/controller.v1/common/job_controller.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/pod_test.go
pkg/controller.v1/common/service.go
pkg/util/labels/labels.go
pkg/util/labels/labels_test.go
test_job/controller.v1/test_job/test_job_controller.go

Add a label for operator name.
Mark non-fully-qualified labels as Deprecated.
Fixes #148
Pending tasks to be done in future releases #149

Add fully-qualified labels

---

pkg/apis/common/v1/interface.go
pkg/controller.v1/common/job.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/service.go
pkg/controller.v1/common/util.go
pkg/controller.v1/common/util_test.go
pkg/controller.v1/expectation/util.go
pkg/util/logger.go
test_job/controller.v1/test_job/test_job_controller.go

https://github.com/kubeflow/common/pull/135 This change brings some extra side effects and make training operator dependency upgrade fail. Since this change is kind of refactor, we determine to revert it at this moment.
/cc @gaocegege @terrytangyuan @kubeflow/wg-training-leads 
Need two of you to approve the change. 
I kick off an end to end test in tf-operator to verify this is working. https://github.com/kubeflow/tf-operator/pull/1395
This PR unblocks https://github.com/kubeflow/tf-operator/pull/1388 and https://github.com/kubeflow/tf-operator/pull/1383

Revert #135: change rtype to commonv1.ReplicaType

---

.github/workflows/build.yml

#162
Looks like they are back actually

Make goveralls step in ci optional

---

pkg/apis/common/v1/openapi_generated.go
pkg/apis/common/v1/types.go

As mentioned in https://github.com/kubeflow/mpi-operator/pull/434#issuecomment-962420580
```
openapi-gen --input-dirs github.com/kubeflow/mpi-operator/v2/pkg/apis/kubeflow/v2beta1,github.com/kubeflow/common/pkg/apis/common/v1 --output-package github.com/kubeflow/mpi-operator/v2/pkg/apis/kubeflow/v2beta1 --go-header-file hack/boilerplate/boilerplate.go.txt
API rule violation: list_type_missing,github.com/kubeflow/common/pkg/apis/common/v1,JobStatus,Conditions
```
This PR fix this issue.

Fix openapi generate rule violation

---

pkg/apis/common/v1/openapi_generated.go
pkg/apis/common/v1/types.go

Due to #175, rollback the changes of listtype.

Rollback #172 as it introduce hard requirements for the list values to not be empty

---

pkg/apis/common/v1/interface.go
pkg/controller.v1/common/job.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/common/service.go
pkg/controller.v1/common/util.go
pkg/controller.v1/common/util_test.go
pkg/controller.v1/expectation/util.go
pkg/core/job.go
pkg/core/pod.go
pkg/core/service.go
pkg/core/utils.go
pkg/reconciler.v1/common/gang_volcano.go
pkg/reconciler.v1/common/interface.go
pkg/reconciler.v1/common/job.go
pkg/reconciler.v1/common/pod.go
pkg/reconciler.v1/common/pod_test.go
pkg/reconciler.v1/common/service.go
pkg/reconciler.v1/common/service_test.go
pkg/util/labels/labels.go
pkg/util/logger.go
test_job/controller.v1/test_job/test_job_controller.go

Since PR #163 has been stalled for a while, this pr tries to accomplish the same goal: revert rtype from `commonv1.ReplicaType` to `string`.
For any parameters, if it is of type `commonv1.ReplicaType`, it's reverted to `string` in this pr. However, parameters of type `map[commonv1.ReplicaType]{any_value_type}` remain unchanged.
@Jeffwan

Revert ReplicaType to string

---

pkg/controller.v1/common/pod.go

If a pod is in phase failure we have to create a new one.
Currently it was assumed the pod would restart due to a RestartPolicy on the pod level
This doesn't work if the pod fails for a system reason.

Handle pod failures for all policies

---

pkg/util/train/train_util.go

The exitCode check works differently then described in the [API](https://github.com/kubeflow/common/blob/master/pkg/apis/common/v1/types.go#L163-L168)
In addition the document exitCodes for Docker will not appear in a Kubernetes pod status (anymore?)

Fix exitCode check

---

pkg/util/status.go

add JobFailedValidation  referring to https://github.com/kubeflow/training-operator/pull/1705

add JobFailedValidation reason constant

---

go.mod
pkg/controller.v1/common/scheduling.go
pkg/controller.v1/control/podgroup_control.go

Signed-off-by: Yuki Iwai <yuki.iwai.tz@gmail.com>
Currently, when users update CustomJob resources (e.g, TFJob) with `runPolicy.schedulingPolicy` or `replicas` changes, traininig-operator can not update PodGroup.
This means when hpa-controller updates `replicas`, training-operator does not update PodGroup.
So I implemented the logic to update PodGroup.
/assign @zw0610 @johnugeorge @terrytangyuan

Support for PodGroup updates

---

pkg/controller.v1/common/job_controller.go
pkg/controller.v1/common/service_test.go
pkg/controller.v1/common/util.go
pkg/reconciler.v1/common/gang_scheduler_framework.go
pkg/reconciler.v1/common/gang_volcano.go

Signed-off-by: Yuki Iwai <yuki.iwai.tz@gmail.com>
I upgraded PriorityClass apiVersion to scheduling.k8s.io/v1 since scheduling.k8s.io/v1beta1 was removed in Kubernetes v1.22.
ref: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
Fixes: #156

Upgrade PriorityClass apiVersion to scheduling.k8s.io/v1

---

pkg/apis/common/v1/openapi_generated.go
pkg/apis/common/v1/types.go
pkg/controller.v1/common/job_test.go

Set None as default.
Fixes: https://github.com/kubeflow/training-operator/issues/1753

Change the default value of CleanPodPolicy to None in comments.

---

pkg/controller.v1/common/job.go
pkg/controller.v1/common/job_controller.go
pkg/controller.v1/common/pod.go
pkg/controller.v1/control/podgroup_control.go
pkg/reconciler.v1/common/gang_scheduler_framework.go

**What this PR does / why we need it:**
Now supports many gang schedulers(volcano, scheduler-plugins). This PR supports koordinator gang scheduler. 
Related: https://github.com/kubeflow/training-operator/issues/1746

Make scheduler-plugins the default gang scheduler
